### ISSUE TITLE
Move local inside the cycle

### ISSUE THREAD

**Issue by IanaKhitsko** [Art17/TPPS#1]
https://github.com/Art17/TPPS/blob/5dbfc7a0246cfe6dc9f366e55bedcf4fcc9647df/lab2/City.cs#L92

**Comment by Art17** [comment]
> https://github.com/Art17/TPPS/blob/5dbfc7a0246cfe6dc9f366e55bedcf4fcc9647df/lab2/City.cs#L92

Done.
