### ISSUE TITLE
Private member declaration

### ISSUE THREAD

**Issue by IanaKhitsko** [Art17/TPPS#2]
https://github.com/Art17/TPPS/blob/5dbfc7a0246cfe6dc9f366e55bedcf4fcc9647df/lab2/Testcase.cs#L16

NumberOfNeighbours - > numberOfNeighbours
(it seems you use lower case for private members, just style issue)

**Comment by Art17** [comment]
> https://github.com/Art17/TPPS/blob/5dbfc7a0246cfe6dc9f366e55bedcf4fcc9647df/lab2/Testcase.cs#L16
> 
> NumberOfNeighbours - > numberOfNeighbours
> (it seems you use lower case for private members, just style issue)

Upper case is used for constant here.
