### ISSUE TITLE
Remove this

### ISSUE THREAD

**Issue by IanaKhitsko** [Art17/TPPS#3]
https://github.com/Art17/TPPS/blob/5dbfc7a0246cfe6dc9f366e55bedcf4fcc9647df/lab2/Testcase.cs#L55

why this. countryNames , not countryNames ?

**Comment by Art17** [comment]
> https://github.com/Art17/TPPS/blob/5dbfc7a0246cfe6dc9f366e55bedcf4fcc9647df/lab2/Testcase.cs#L55
> 
> why this. countryNames , not countryNames ?

Done.
